### ISSUE TITLE
Setting up a Linux server

### ISSUE THREAD

**Issue by jph00** [jph00/notes#1]
Steps to set up a basic Ubuntu 20.04 server. WIP.

```bash
export DEBIAN_FRONTEND=noninteractive
sudo add-apt-repository -y ppa:apt-fast/stable
sudo apt-get update
sudo apt-get -y install apt-fast
sudo apt-fast -y upgrade
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
sudo apt-add-repository -y https://cli.github.com/packages
sudo apt-fast -y install vim-nox python3-powerline rsync ubuntu-drivers-common python3-pip ack-grep lsyncd wget bzip2 ca-certificates git rsync build-essential curl grep sed dpkg sudo libglib2.0-dev zlib1g-dev lsb-release tmux less htop ctags openssh-client python-is-python3 python3-pip python3-dev dos2unix gh pigz 

cat << 'EOF' >> ~/.ssh/config
Host *
ServerAliveInterval 60
StrictHostKeyChecking no
Host github.com
User git
Port 22
Hostname github.com
TCPKeepAlive yes
IdentitiesOnly yes
EOF
chmod 600 ~/.ssh/config

# This will reboot your machine to install upgrades
sudo shutdown -r now
```

After it reboots:

```
sudo dpkg-reconfigure --priority=low unattended-upgrades
```

You may also want to install  fork of my [dotfiles](https://github.com/fastai/dotfiles/). Be sure to update `.gitconfig` with your email/name.

**Comment by hamelsmu** [comment]
This is a pretty interesting way to take notes.  I wish there was a better search for issues though...., will be curious to hear your thoughts.  This looks like an even easier way to write up TILs which I am a big fan of.

**Comment by deep-diver** [comment]
I would use this as a personal note, and look back what I have done every week or so along with `fastrelease`.

**Comment by joedockrill** [comment]
Woah. I set up Ubuntu on my windows box yesterday. By the time I'd finished I was wishing I'd kept notes!

**Comment by PuneethaPai** [comment]
@jph00 How about using wiki instead of issues? I feel Wiki's are better suit for taking notes, vs issues. 😃 

@hamelsmu  we can use top `github search` to search `in this repository`. Thus our notes become searchable. 
It even supports issues, wikis, code, commits, etc.

### For example:
<img width="782" alt="image" src="https://user-images.githubusercontent.com/21996583/93669923-dbfbf000-fab4-11ea-84d6-76a5e5aebdcf.png">

**Comment by jph00** [comment]
GH Wiki doesn't let you paste images, sadly.

**Comment by jph00** [comment]
This is now implemented as `ubuntu-initial.sh` in https://github.com/fastai/fastsetup/
